---
title: "Amount of offspring for C. elegans incubated in different substances"
author: "Thijmen van Brenk"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(readxl)
```

# inspecting the data
```{r inspecting the data}

offspring <- read_excel(here("assignment_1/data/CE.LIQ.FLOW.062_Tidydata.xlsx"), sheet = 1)

# we want to see if the data for the experimental conditions have been imported correctly
offspring %>% select(c("expType", "RawData", "compName", "compConcentration"))

# as we can see, the rawdata should have been an integer, the compname and expType should have been a factor and the compconcentration should have been a double. lets change that

offspring$RawData <- as.integer(offspring$RawData)
offspring$compName <- as.factor(offspring$compName)
offspring$expType <- as.factor(offspring$expType)

offspring_tidy <- offspring
offspring_tidy$compConcentration <- as.numeric(offspring_tidy$compConcentration)

# one of the values in compconcentration is accidentally classified as a character in excel and has now turned into a NA value, we will change this value manually.

character_placement <- which(is.na(offspring_tidy$compConcentration))
character_value <- offspring$compConcentration[character_placement] %>% str_replace(",", ".") %>% parse_number()
offspring_tidy$compConcentration[character_placement] <- character_value

# lets check one last time if the data types are correct.
offspring %>% select(c("RawData", "compName", "compConcentration"))

# they are so we can now use the data for further analysis
```

# graphical visualization of the data
```{r graphical visualization of the data}

offspring_tidy %>%
  ggplot(aes(x = log10(compConcentration + 0.0001), y = RawData)) +
  geom_jitter(aes(shape = expType, colour = compName), width = .1)

```

the positive control of this experiment is Ethanol and the negative control is no added substance.

